- name: Export all secrets to env variables
  # You may pin to the exact commit or the version.
  # uses: oNaiPs/secrets-to-env-action@80af0bb8dba2db50965bfb3ed5950275594baf02
  uses: oNaiPs/secrets-to-env-action@v1.2
  with:
    secrets: ${{ toJSON(secrets) }}
- run: echo "Value of MY_SECRET: $MY_SECRET"
